apiVersion: zookeeper.stackable.tech/v1
kind: ZookeeperCluster
metadata:
  name: simple
spec:
  version: 3.5.8
  servers:
    selectors:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-1.stackable.demo
                - worker-2.stackable.demo
                - worker-3.stackable.demo
        instances: 1
        instancesPerNode: 1
