apiVersion: kafka.stackable.tech/v1
kind: KafkaCluster
metadata:
  name: simple
spec:
  version:
    kafka_version: 2.8.0
  zookeeperReference:
    namespace: default
    name: simple
  brokers:
    selectors:
      default:
        selector:
          matchExpressions:
            - operator: In
              key: kubernetes.io/hostname
              values:
                - worker-1.stackable.demo
                - worker-2.stackable.demo
                - worker-3.stackable.demo
        instances: 1
        instancesPerNode: 1